# Only this file selects a Gazebo ABI. The terrain engine has no simulator links.
if(POLICY CMP0146)
    cmake_policy(SET CMP0146 OLD)
endif()

# Released gz-sim development packages also describe the optional GUI in the
# server library's CMake dependencies. Suppress that discovery for server builds
# and remove its interface edge. The actual server imported library, include
# directories, version checks, and all non-GUI dependencies still come from the
# installed Gazebo package configuration (no guessed library filenames).
function(dynamic_terrain_find_server package version gui_package)
    set(CMAKE_DISABLE_FIND_PACKAGE_${gui_package} TRUE)
    set(CMAKE_DISABLE_FIND_PACKAGE_Qt5 TRUE)
    set(CMAKE_DISABLE_FIND_PACKAGE_Qt6 TRUE)
    # Do not propagate REQUIRED to this package's unconditional GUI searches.
    find_package(${package} ${version} CONFIG QUIET)
    if(NOT TARGET ${package}::${package})
        message(FATAL_ERROR "Gazebo ${GZ_DISTRO} requires ${package} ${version} development files. Set CMAKE_PREFIX_PATH to that Gazebo installation.")
    endif()
    get_target_property(server_links ${package}::${package} INTERFACE_LINK_LIBRARIES)
    if(server_links)
        list(FILTER server_links EXCLUDE REGEX "^${gui_package}(::.*)?$")
        set_property(TARGET ${package}::${package} PROPERTY
            INTERFACE_LINK_LIBRARIES "${server_links}")
    endif()
endfunction()

if(GZ_DISTRO STREQUAL "harmonic")
    find_package(gz-cmake3 REQUIRED)
    if(BUILD_GUI)
        find_package(gz-sim8 8 REQUIRED)
        find_package(gz-gui8 8 REQUIRED)
        find_package(Qt5 REQUIRED COMPONENTS Core Quick Qml)
        set(DYNAMIC_TERRAIN_GUI_TARGET gz-gui8::gz-gui8)
        set(DYNAMIC_TERRAIN_QT_TARGET Qt5::Quick)
    else()
        dynamic_terrain_find_server(gz-sim8 8 gz-gui8)
    endif()
    find_package(gz-plugin2 2 REQUIRED COMPONENTS register loader)
    find_package(gz-rendering8 8 REQUIRED COMPONENTS ogre2)
    set(DYNAMIC_TERRAIN_SIM_TARGET gz-sim8::gz-sim8)
    set(DYNAMIC_TERRAIN_RENDER_TARGET gz-rendering8::ogre2)
    set(DYNAMIC_TERRAIN_RENDER_LIBRARY_TARGET gz-rendering8::gz-rendering8-ogre2)
    set(DYNAMIC_TERRAIN_PLUGIN_TARGET gz-plugin2::register)
    set(DYNAMIC_TERRAIN_PLUGIN_LOADER_TARGET gz-plugin2::loader)
    set(DYNAMIC_TERRAIN_BACKEND_DEFINITION DYNAMIC_TERRAIN_GZ_HARMONIC)
elseif(GZ_DISTRO STREQUAL "jetty")
    find_package(gz-cmake 5 REQUIRED)
    if(BUILD_GUI)
        find_package(gz-sim 10 REQUIRED)
        find_package(gz-gui 10 REQUIRED)
        find_package(Qt6 6.4 REQUIRED COMPONENTS Core Quick Qml)
        set(DYNAMIC_TERRAIN_GUI_TARGET gz-gui::gz-gui)
        set(DYNAMIC_TERRAIN_QT_TARGET Qt6::Quick)
    else()
        dynamic_terrain_find_server(gz-sim 10 gz-gui)
    endif()
    find_package(gz-plugin 4 REQUIRED COMPONENTS register loader)
    find_package(gz-rendering 10 REQUIRED COMPONENTS ogre2)
    set(DYNAMIC_TERRAIN_SIM_TARGET gz-sim::gz-sim)
    set(DYNAMIC_TERRAIN_RENDER_TARGET gz-rendering::ogre2)
    set(DYNAMIC_TERRAIN_RENDER_LIBRARY_TARGET gz-rendering::gz-rendering-ogre2)
    set(DYNAMIC_TERRAIN_PLUGIN_TARGET gz-plugin::register)
    set(DYNAMIC_TERRAIN_PLUGIN_LOADER_TARGET gz-plugin::loader)
    set(DYNAMIC_TERRAIN_BACKEND_DEFINITION DYNAMIC_TERRAIN_GZ_JETTY)
endif()

find_package(GzOGRE2 2.3 REQUIRED)
if(NOT TARGET GzOGRE2::GzOGRE2)
    message(FATAL_ERROR "The selected rendering adapter requires the OgreNext 2.3 development package used by Gazebo.")
endif()
